image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir public
  - mv api/ public/
  - mv *.html public/
  - mv *.ttf public/
  - mv *.css public/
  artifacts:
    paths:
    - public/
  only:
  - master
